Team-Teamble/Teamble-Server

functions/constants/responseMessage.js, functions/db/index.js, functions/db/project.js, functions/db/tag.js, functions/db/type.js, functions/db/user.js, functions/lib/jwtHandlers.js, functions/package-lock.json, functions/package.json
=> [ADD] db query

README.md, functions/constants/responseMessage.js
=> [CORRECT] change dummy to metadata

functions/api/routes/user/index.js, functions/api/routes/user/userProfileMetadataGET.js, functions/constants/responseMessage.js, functions/db/field.js, functions/db/position.js, functions/db/type.js
* #13
* 유저 프로필 수정 메타데이터 받기
* 삭제된 response message 추가하고, "전체" row를 빼는 쿼리를 따로 작성하였습니다.
=> [FEAT] userProfileMetadataGET 구현 #13

functions/api/routes/auth/authLoginPOST.js
* #2
* 유저 로그인
* 로그인된 유저의 정보를 모두 불러옵니다.
=> [FEAT] authLoginPOST 구현 #2

functions/api/routes/user/index.js, functions/api/routes/user/userProfileGET.js, functions/api/routes/user/userProfilePUT.js, functions/constants/responseMessage.js, functions/db/index.js, functions/db/user.js, functions/db/userField.js, functions/db/userPosition.js
* #17
* 유저 프로필 업데이트 기능
* 업데이트를 DELETE 후 INSERT 하는 방식으로 구현하였습니다.
* 클라이언트에게 먼저 response를 보내준 후 DB를 업데이트하는 방식으로 구현하였습니다.
=> [FEAT] userProfilePUT 구현 #17

.firebaserc, .gitignore, functions/config/dbConfig.js, functions/config/firebaseClient.js, functions/index.js, functions/package.json
=> [REFACTOR] 개발 / 배포 환경 변수 분리

db.sql, dummy.sql
=> [ADD] sql files

functions/api/routes/member/memberMetadataGET.js, functions/api/routes/project/index.js, functions/api/routes/project/projectMetadataGET.js, functions/api/routes/project/projectSearchMetadata.js, functions/constants/responseMessage.js
* #33 
* 프로젝트 생성 페이지 메타데이터 받기
* response message에서 `FIND`를 `SEARCH`로 변경
=> [FEAT] projectSearchMetadata 구현 #33

functions/api/routes/project/index.js, functions/api/routes/project/projectPhotoPOST.js, functions/constants/responseMessage.js, functions/db/project.js
* #30
* 프로젝트 사진 변경
* 사진을 `form-data` `file` 형식으로 받아서 firebase storage에 저장 후 url 반환
=> [FEAT] projectPhotoPOST 구현 #30

functions/api/routes/user/index.js, functions/api/routes/user/userPokeUserPOST.js, functions/api/routes/user/userProfileGET.js, functions/db/index.js, functions/db/userPoke.js
* #46 
* 유저 콕찌르기
* 콕찌르기 시, 찌르기 당한 user의 알림 확인 여부(`is_checked`)를 `false`로 업데이트 했습니다.
=> [FEAT] userPokeUserPOST 구현 #46

functions/api/routes/user/index.js, functions/api/routes/user/userPokeUserGET.js, functions/api/routes/user/userProfileGET.js, functions/api/routes/user/userProfilePUT.js, functions/api/routes/user/userProfilePhotoPOST.js, functions/db/user.js, functions/db/userPoke.js
* #48 
* 마이페이지에서 나를 찔러본 사람 조회
* 최신순 조회
=> [FEAT] userPokeUserGET 구현 #48

functions/api/routes/member/memberPOST.js, functions/api/routes/project/projectTopGET.js, functions/api/routes/user/index.js, functions/api/routes/user/userPokeUserDELETE.js, functions/api/routes/user/userPokeUserGET.js, functions/db/user.js, functions/db/userPoke.js
=> [FEAT] userPokeUserDELETE 구현 #50

functions/api/routes/project/projectGET.js, functions/api/routes/user/index.js, functions/api/routes/user/userPokeProjectPOST.js, functions/db/index.js, functions/db/projectPoke.js, functions/db/user.js
* #51
* 팀 지원하기 
* 팀 지원하기를 당한 프로젝트의 유저 is_checked = false로 설정
=> [FEAT] userPokeProjectPOST 구현 #51

functions/api/routes/user/index.js, functions/api/routes/user/userPokeProjectGET.js, functions/api/routes/user/userPokeProjectPOST.js, functions/db/projectPoke.js, functions/db/user.js
* #54
* 내 프로젝트에 지원한 사람
* Member정보를 최신순으로 추출
=> [FEAT] userPokeProjectGET 구현 #54

functions/api/routes/user/index.js, functions/api/routes/user/userPokeProjectDELETE.js, functions/db/projectPoke.js
* #56
*  내 프로젝트에 지원한 사람 삭제
*  내 프로젝트에 지원한 사람 삭제 후 내 프로젝트에 지원한 사람 리스트 반환
=> [FEAT] userPokeProjectDELETE 구현 #56

functions/api/routes/project/index.js, functions/api/routes/project/projectPOST.js, functions/api/routes/project/projectSearchPOST.js, functions/db/project.js, functions/db/projectPosition.js
* #44 
* 프로젝트 찾기 - 조회
* 각 필터별로 projectId 값을 추출해 배열을 만들고 그들의 공통 projectId를 찾아서 구현하였습니다.
=> [FEAT] projectSearchPOST 구현 #44

functions/.env.example, functions/api/routes/auth/authLoginPOST.js
=> [CHORE] signInWithEmailAndPassword

README.md, functions/api/routes/auth/authLoginPOST.js, functions/api/routes/auth/authSignupPOST.js
=> [FIX] firebase error

functions/api/routes/auth/authSignupPOST.js
=> [CHORE] delete duplicate elseif statement

functions/api/routes/project/projectSearchPOST.js
=> [CHORE] rename project to projectCard

functions/api/routes/auth/authLoginGET.js, functions/api/routes/auth/authLoginPOST.js, functions/api/routes/auth/authSignupPOST.js, functions/api/routes/project/projectPOST.js
* add auth slack message
* modify project structure
* handle memberId null
=> [CHORE] projectPOST.js

functions/api/routes/user/userPokeProjectPOST.js
* userPokeProjectPOST response body 구조 변경
=> [CHORE] userPokeProject structure

functions/api/routes/auth/authLoginGET.js, functions/api/routes/auth/authLoginPOST.js, functions/api/routes/auth/authSignupPOST.js, functions/api/routes/member/memberMetadataGET.js, functions/api/routes/member/memberPOST.js, functions/api/routes/project/projectDELETE.js, functions/api/routes/project/projectGET.js, functions/api/routes/project/projectMemberPOST.js, functions/api/routes/project/projectMetadataGET.js, functions/api/routes/project/projectPOST.js, functions/api/routes/project/projectPhotoPOST.js, functions/api/routes/project/projectSearchMetadataGET.js, functions/api/routes/project/projectSearchPOST.js, functions/api/routes/project/projectTopGET.js, functions/api/routes/user/userPokeProjectDELETE.js, functions/api/routes/user/userPokeProjectGET.js, functions/api/routes/user/userPokeProjectPOST.js, functions/api/routes/user/userPokeUserDELETE.js, functions/api/routes/user/userPokeUserGET.js, functions/api/routes/user/userPokeUserPOST.js, functions/api/routes/user/userProfileGET.js, functions/api/routes/user/userProfileMetadataGET.js, functions/api/routes/user/userProfilePUT.js, functions/api/routes/user/userProfilePhotoPOST.js
* modify project, member, user slack message
=> [CHORE] project, member, user slack message

db_query/4_project.sql
* 프로젝트 테이블의 유저 아이디가 중복된 경우 row 하나만 남기고 나머지는 `is_closed = true`로 처리했습니다.
=> [CHORE] change db queries where is_closed is true

functions/api/routes/user/userProfilePUT.js, functions/db/project.js
* 유저 프로필 수정 시 response message 반환 위치 수정
* 주목할만한 프로젝트 조회 시 최신순으로 안되는 에러 수정
=> [FIX] update profile, get top project

db_query/4_project.sql
* 주목할만한 프로젝트에서 보여줄 프로젝트들의 생성 날짜 변경
=> [CHORE] change project's created date

functions/db/project.js
* 프로젝트 찾기 뷰 created_at DESC 로 정렬
=> [FIX] order by created_at DESC

db_query/4_project.sql, functions/db/user.js
=> [CHORE] getMemberByMemberId

functions/api/routes/user/userPokeProjectGET.js
* modify userPokeProjectGET.js
=> [CHORE] userPokeProjectGET.js

functions/db/user.js
=> [CHORE] id 중복 처리
